/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author gonzalo
 */
public final class VistaIngresoFrecuencia extends javax.swing.JFrame {
    private final ControladorSistema controladorSistema;
    private Usuario usuarioLogeado = null;
    /**
     * Creates new form VistaIngresoFrecuencia
     * @param usuario
     */
    public VistaIngresoFrecuencia(Usuario usuario) {
        this.controladorSistema = ControladorSistema.getInstancia();
        initComponents();
        this.usuarioLogeado = usuario;
        lblUsuarioLogeado.setText(usuario.toString());
        cargarAeropuertos();
        cargarDiasSemana();
        cargarFrecuencias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuarioLogeado = new javax.swing.JLabel();
        lstAeropuertoOrigen = new java.awt.List();
        lblAeropuertoOrigen = new javax.swing.JLabel();
        lblAeropuertoDestino = new javax.swing.JLabel();
        lstAeropuertoDestino = new java.awt.List();
        btnIngresar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lstDiasSemana = new java.awt.List();
        lblDiasSemana = new javax.swing.JLabel();
        lblHoraPartida = new javax.swing.JLabel();
        lblDuracion = new javax.swing.JLabel();
        jsfDuracion = new com.toedter.components.JSpinField();
        lblHoraPartida2 = new javax.swing.JLabel();
        JtcHoraPartida = new lu.tudor.santec.jtimechooser.JTimeChooser();
        lblIngresar = new javax.swing.JLabel();
        lblVerFrecuencias = new javax.swing.JLabel();
        lstFrecuenciasCompañia = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblUsuarioLogeado.setText("Nombre");

        lblAeropuertoOrigen.setText("Selecciona un origen:");

        lblAeropuertoDestino.setText("Selecciona un destino:");

        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        lstDiasSemana.setMultipleMode(true);

        lblDiasSemana.setText("Selecciona los días:");

        lblHoraPartida.setText("Hora de partida:");

        lblDuracion.setText("Duración:");

        jsfDuracion.setValue(60);

        lblHoraPartida2.setText("min");

        JtcHoraPartida.setDoubleBuffered(true);
        JtcHoraPartida.setHighlightingColor(java.awt.Color.lightGray);
        JtcHoraPartida.setName(""); // NOI18N
        JtcHoraPartida.setOpaque(true);
        JtcHoraPartida.setShowSeconds(false);

        lblIngresar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblIngresar.setText("Ingresar frecuencia");

        lblVerFrecuencias.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblVerFrecuencias.setText("Frecuencias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(175, 809, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIngresar)
                            .addComponent(lblDiasSemana)
                            .addComponent(lblAeropuertoOrigen)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lstAeropuertoOrigen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lstAeropuertoDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lstDiasSemana, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblAeropuertoDestino))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JtcHoraPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHoraPartida)
                                    .addComponent(lblDuracion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jsfDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblHoraPartida2)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblUsuarioLogeado)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblVerFrecuencias)
                                    .addComponent(lstFrecuenciasCompañia, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblUsuarioLogeado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblVerFrecuencias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lstFrecuenciasCompañia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(lblIngresar)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAeropuertoOrigen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lstAeropuertoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHoraPartida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtcHoraPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAeropuertoDestino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lstAeropuertoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(lblDiasSemana))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDuracion)
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jsfDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHoraPartida2))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lstDiasSemana, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
        new VistaLogin().setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        String aeropuertoOrigen = lstAeropuertoOrigen.getSelectedItem();
        String aeropuertoDestino = lstAeropuertoDestino.getSelectedItem();
        String[] listaDiasSemana = lstDiasSemana.getSelectedItems();
        String horaPartida = JtcHoraPartida.getFormatedTime();
        int duracionEstimada = jsfDuracion.getValue();
        
        if(validarInfo(aeropuertoOrigen, aeropuertoDestino, listaDiasSemana, horaPartida, duracionEstimada)) {
            ingresarFrecuencia(aeropuertoOrigen, aeropuertoDestino, listaDiasSemana, horaPartida, duracionEstimada, this.usuarioLogeado);
            JOptionPane.showMessageDialog(this, "Frecuencia ingresada");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed
    
    public boolean validarInfo(String aeropuertoOrigen, String aeropuertoDestino, String[] listaDiasSemana, String horaPartida, int duracionEstimada) {
        ArrayList<Object> validacion = controladorSistema.validarFrecuencia(aeropuertoOrigen, aeropuertoDestino, listaDiasSemana, horaPartida, duracionEstimada, this.usuarioLogeado);
        
        if(validacion.size() == 2) {
            JOptionPane.showMessageDialog(this, validacion.get(0));
            return (boolean)validacion.get(1);
        } else {
           return (boolean)validacion.get(0);
        }
    }
    
    public void ingresarFrecuencia(String aeropuertoOrigen, String aeropuertoDestino, String[] listaDiasSemana, String horaPartida, int duracion, Usuario usuario) {
        this.controladorSistema.ingresarFrecuencia(aeropuertoOrigen, aeropuertoDestino, listaDiasSemana, horaPartida, duracion, usuario);
        cargarFrecuencias();
    }

    public void cargarAeropuertos() {
        ArrayList<Aeropuerto> aeropuertos = controladorSistema.getListaAeropuertos();

        for(Aeropuerto a : aeropuertos) {
            if(a != null) {
                lstAeropuertoOrigen.add(a.getCiudad());
                lstAeropuertoDestino.add(a.getCiudad());
            }
        }
        lstAeropuertoOrigen.select(0);
        lstAeropuertoDestino.select(0);
    }
    
    public void cargarDiasSemana() {
        ArrayList<String> diasSemana = controladorSistema.getListaDiasSemana();

        for(String d : diasSemana) {
            if(d != null) {
                lstDiasSemana.add(d);
            }
        }
        lstDiasSemana.select(0);
    }    
    
    public void cargarFrecuencias() {
        lstFrecuenciasCompañia.removeAll();
        ArrayList<Frecuencia> frecuencias = controladorSistema.getListaFrecuencias(this.usuarioLogeado.getNombreTrabajo());
        
        for(Frecuencia f : frecuencias) {
            if(f != null) {
                String dias = controladorSistema.getLetraDiasSemana(f);
                for (Vuelo v : f.getVuelos()) {
                lstFrecuenciasCompañia.add(v.getNumero() + " - " + f.getAeropuertoOrigen().getNombre() + " - " + f.getEstadoAeropuertoOrigen()+ " - " + 
                        f.getAeropuertoDestino().getNombre() + " - " + f.getEstadoAeropuertoDestino()+ " - " + dias + " - " + f.getHoraPartida() + " - " + f.getDuracionEstimada() + " min.");   
                }
            }
        }
        lstFrecuenciasCompañia.select(0);
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lu.tudor.santec.jtimechooser.JTimeChooser JtcHoraPartida;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private com.toedter.components.JSpinField jsfDuracion;
    private javax.swing.JLabel lblAeropuertoDestino;
    private javax.swing.JLabel lblAeropuertoOrigen;
    private javax.swing.JLabel lblDiasSemana;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblHoraPartida;
    private javax.swing.JLabel lblHoraPartida2;
    private javax.swing.JLabel lblIngresar;
    private javax.swing.JLabel lblUsuarioLogeado;
    private javax.swing.JLabel lblVerFrecuencias;
    private java.awt.List lstAeropuertoDestino;
    private java.awt.List lstAeropuertoOrigen;
    private java.awt.List lstDiasSemana;
    private java.awt.List lstFrecuenciasCompañia;
    // End of variables declaration//GEN-END:variables
}
