/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ort.edu.uy.obligatorio.vista;

import ort.edu.uy.obligatorio.modelo.*;
import ort.edu.uy.obligatorio.controlador.ControladorSistema;
import java.util.ArrayList;

/**
 *
 * @author gonzalo
 */
public final class VistaMonitoreo extends javax.swing.JFrame {
    private final ControladorSistema controladorSistema;
    private Usuario usuarioLogeado = null;
    /**
     * Creates new form VistaMonitoreo
     * @param usuario
     */
    public VistaMonitoreo(Usuario usuario) {
        this.controladorSistema = ControladorSistema.getInstancia();
        initComponents();
        this.usuarioLogeado = usuario;
        lblUsuarioLogeado.setText(usuario.toString());
        cargarPartidas();
        cargarLlegadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPartidas = new javax.swing.JLabel();
        lblUsuarioLogeado = new javax.swing.JLabel();
        lstPartidas = new java.awt.List();
        lstLlegadas = new java.awt.List();
        lblLlegadas = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        lblPartidas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPartidas.setText("Partidas");

        lblUsuarioLogeado.setText("Nombre");

        lblLlegadas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblLlegadas.setText("Llegadas");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPartidas)
                            .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 333, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblLlegadas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsuarioLogeado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lstLlegadas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                            .addComponent(lstPartidas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(46, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarioLogeado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPartidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLlegadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstLlegadas, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    public void cargarPartidas() {
        lstPartidas.removeAll();
        ArrayList<Frecuencia> frecuencias = controladorSistema.getListaPartidas((Aeropuerto)this.usuarioLogeado.getTrabajo());
        
        for(Frecuencia f : frecuencias) {
            for (Vuelo v : f.getVuelos()) {
                if(v.getHoraPartida() != null && v.getHoraLlegada() == null) {
                    lstPartidas.add(v.getNumero() + " - " + f.getCompañia().getNombre() + " - " +  f.getAeropuertoDestino().getNombre() + " - " + v.getEstado());     
                }
            }
        }
        lstPartidas.select(0);
    }
    
    public void cargarLlegadas() {
        lstLlegadas.removeAll();
        ArrayList<Frecuencia> frecuencias = controladorSistema.getListaLlegadas((Aeropuerto)this.usuarioLogeado.getTrabajo());
        
        for(Frecuencia f : frecuencias) {
            for (Vuelo v : f.getVuelos()) {
                if(v.getHoraLlegada() != null) {
                    lstLlegadas.add(v.getNumero() + " - " + f.getCompañia().getNombre() + " - " + f.getAeropuertoOrigen().getNombre() + " - " + v.getEstado());     
                }
            }
        }
        lstLlegadas.select(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblLlegadas;
    private javax.swing.JLabel lblPartidas;
    private javax.swing.JLabel lblUsuarioLogeado;
    private java.awt.List lstLlegadas;
    private java.awt.List lstPartidas;
    // End of variables declaration//GEN-END:variables
}
