/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ort.edu.uy.obligatorio.vista;

import ort.edu.uy.obligatorio.modelo.*;
import ort.edu.uy.obligatorio.controlador.ControladorSistema;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author gonzalo
 */
public final class VistaIngresarPartidaVuelo extends javax.swing.JFrame {
    private final ControladorSistema controladorSistema;
    private Usuario usuarioLogeado = null;
    private VistaMonitoreo vistaMonitoreo = null;
    /**
     * Creates new form VistaIngresarPartidaVuelo
     * @param usuario
     * @param vistaMonitoreo
     */
    public VistaIngresarPartidaVuelo(Usuario usuario, VistaMonitoreo vistaMonitoreo) {
        this.controladorSistema = ControladorSistema.getInstancia();
        initComponents();
        this.usuarioLogeado = usuario;
        this.vistaMonitoreo = vistaMonitoreo;
        lblUsuarioLogeado.setText(usuario.toString());
        cargarFrecuenciasAprobadas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuarioLogeado = new javax.swing.JLabel();
        lblVerFrecuencias = new javax.swing.JLabel();
        lstFrecuencias = new java.awt.List();
        btnSalir = new javax.swing.JButton();
        btnIngresarPartidaVuelo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblUsuarioLogeado.setText("Nombre");

        lblVerFrecuencias.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblVerFrecuencias.setText("Frecuencias");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnIngresarPartidaVuelo.setText("Ingresar");
        btnIngresarPartidaVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarPartidaVueloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsuarioLogeado)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnIngresarPartidaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lstFrecuencias, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVerFrecuencias))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuarioLogeado)
                .addGap(33, 33, 33)
                .addComponent(lblVerFrecuencias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lstFrecuencias, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnIngresarPartidaVuelo))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
        new VistaMenuAeropuerto(this.usuarioLogeado, this.vistaMonitoreo).setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIngresarPartidaVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarPartidaVueloActionPerformed
        if(lstFrecuencias.getItemCount() > 0) {
            int confirmarAccion = JOptionPane.showConfirmDialog(this, "Seguro deseas ingresar partida de vuelo?");

            switch(confirmarAccion) {
                case 0: {
                    String frecuenciaSeleccionada = lstFrecuencias.getSelectedItem();
                    String[] f = frecuenciaSeleccionada.split(" - ");
                    controladorSistema.ingresarPartidaVuelo(f, (Aeropuerto)this.usuarioLogeado.getTrabajo());
                    cargarFrecuenciasAprobadas();
                    this.vistaMonitoreo.cargarPartidas();
                }
                default: {
                    JOptionPane.getRootFrame().dispose();
                }
            }   
        }
    }//GEN-LAST:event_btnIngresarPartidaVueloActionPerformed

    public void cargarFrecuenciasAprobadas() {
        lstFrecuencias.removeAll();
        ArrayList<Frecuencia> frecuencias = controladorSistema.getListaFrecuenciasAprobadasOrigen((Aeropuerto)this.usuarioLogeado.getTrabajo());
        String diaActual = controladorSistema.getDiaActual();
        
        for(Frecuencia f : frecuencias) {
            for (Vuelo v : f.getVuelos()) {
                if(v.getHoraPartida() == null) {
                    lstFrecuencias.add(diaActual + " - " + v.getNumero() + " - " + f.getAeropuertoDestino().getNombre() + " - " + f.getHoraPartida());   
                }
            }
        }
        lstFrecuencias.select(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarPartidaVuelo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblUsuarioLogeado;
    private javax.swing.JLabel lblVerFrecuencias;
    private java.awt.List lstFrecuencias;
    // End of variables declaration//GEN-END:variables
}
